{
  "Faults": [
    {
      "latitude": 50.89833208641456,
      "type": "PSI",
      "reference": "215616",
      "etaUpdate": true,
      "affectedCustomerCount": 100,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "932b4a7c-907c-423d-9dab-fc729f470efc",
      "minLongitude": -2.3571,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.3322498592628746,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-16T07:30:00.000+0000",
      "estimatedRestoration": "2023-04-22T15:30:00.000+0000",
      "message": "We're sorry for the loss of supply. The reason you're currently without power is a planned outage in the areas listed. We have turned off your electricity supply to allow us to safely carry out essential work to our electrical equipment. By doing this, it'll help us to improve the reliability of our service to you for the future. If you have any questions or require more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) with reference  '215616'. You will have received a letter from us confirming your power will be interrupted with specific information relating to your property. If you did not receive this letter, you can assume your power will not be interrupted.",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/215616",
      "maxLongitude": -2.3084,
      "minLatitude": 50.8804,
      "name": "DT10 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "DT10 2AF",
        "DT10 2AG",
        "DT10 2AJ",
        "DT10 2AL",
        "DT10 2AN",
        "DT10 2AP",
        "DT10 2AQ",
        "DT10 2AW",
        "DT10 2DW"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.3571,
              50.9148
            ],
            [
              -2.3084,
              50.9148
            ],
            [
              -2.3084,
              50.8804
            ],
            [
              -2.3571,
              50.8804
            ],
            [
              -2.3571,
              50.9148
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.9148,
      "etrUpdate": true
    },
    {
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-22T01:43:00.000+0000",
      "latitude": 51.69658163226935,
      "estimatedRestoration": "2023-04-22T07:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KU7416'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KU7416",
      "reference": "KU7416",
      "etaUpdate": true,
      "affectedCustomerCount": 21,
      "name": "GL7 Area",
      "otherUpdate": true,
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "GL7 6HD",
        "GL7 6HP",
        "GL7 6JL"
      ],
      "location": {
        "coordinates": [
          -1.9519751211155942,
          51.69658163226935
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2023-04-22T02:45:00.000+0000",
      "UUID": "34dfae5f-ee34-4ea2-a3a7-b55479b7e543",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "etrUpdate": true,
      "longitude": -1.9519751211155942,
      "resolved": false
    },
    {
      "latitude": 51.14443025792397,
      "type": "HV",
      "reference": "KU7434",
      "etaUpdate": true,
      "affectedCustomerCount": 3,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "7b5e71f6-b049-4962-8133-e526a07a6ab6",
      "minLongitude": -1.0452,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.9829783624620634,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-22T02:59:00.000+0000",
      "estimatedRestoration": "2023-04-22T06:05:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KU7434'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KU7434",
      "maxLongitude": -0.973,
      "minLatitude": 51.1116,
      "name": "GU34 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "GU34 1AA",
        "GU34 1AB",
        "GU34 1BA",
        "GU34 1EN",
        "GU34 1ER",
        "GU34 1EU",
        "GU34 1EW",
        "GU34 1GS",
        "GU34 1HL",
        "GU34 1HQ",
        "GU34 1LG",
        "GU34 1NE",
        "GU34 1NH",
        "GU34 5HH"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.0452,
              51.1502
            ],
            [
              -0.973,
              51.1502
            ],
            [
              -0.973,
              51.1116
            ],
            [
              -1.0452,
              51.1116
            ],
            [
              -1.0452,
              51.1502
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-04-22T03:50:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.1502,
      "etrUpdate": true
    },
    {
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-22T03:08:00.000+0000",
      "latitude": 50.838031434579456,
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. We are working hard to get the power back on as quickly as we can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KU7438'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KU7438",
      "reference": "KU7438",
      "maxLongitude": -2.1335,
      "etaUpdate": true,
      "minLatitude": 50.8264,
      "name": "DT11 Area",
      "otherUpdate": true,
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "DT11 0QB",
        "DT11 9FH",
        "DT11 9FJ",
        "DT11 9FT",
        "DT11 9NH",
        "DT11 9NQ",
        "DT11 9NX",
        "DT11 9NY",
        "DT11 9NZ",
        "DT11 9PA",
        "DT11 9PB",
        "DT11 9PD"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.202,
              50.879
            ],
            [
              -2.1335,
              50.879
            ],
            [
              -2.1335,
              50.8264
            ],
            [
              -2.202,
              50.8264
            ],
            [
              -2.202,
              50.879
            ]
          ]
        ],
        "type": "Polygon"
      },
      "UUID": "39aa88a1-b83b-47a2-8dbd-9f17ceb53668",
      "region": "com.opengrid.geo.world.europe.gb",
      "minLongitude": -2.202,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "maxLatitude": 50.879,
      "etrUpdate": true,
      "longitude": -2.1469613788438044,
      "resolved": false
    },
    {
      "latitude": 50.836846935584035,
      "type": "HV",
      "reference": "KU7437",
      "etaUpdate": true,
      "affectedCustomerCount": 9,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "1976f59a-5ac5-45b1-beb7-1f7b236d88f4",
      "minLongitude": -2.1598,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.1449553060495723,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-22T03:07:00.000+0000",
      "estimatedRestoration": "2023-04-22T06:10:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KU7437'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KU7437",
      "maxLongitude": -2.1408,
      "minLatitude": 50.8321,
      "name": "DT11 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "DT11 9LG",
        "DT11 9NF",
        "DT11 9NG",
        "DT11 9NP",
        "DT11 9NS",
        "DT11 9NT",
        "DT11 9NW",
        "DT11 9NY",
        "DT11 9PJ",
        "DT11 9PL",
        "DT11 9PN"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.1598,
              50.8419
            ],
            [
              -2.1408,
              50.8419
            ],
            [
              -2.1408,
              50.8321
            ],
            [
              -2.1598,
              50.8321
            ],
            [
              -2.1598,
              50.8419
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.8419,
      "etrUpdate": true
    },
    {
      "latitude": 50.833080726871266,
      "type": "LV",
      "reference": "KU7457",
      "etaUpdate": true,
      "affectedCustomerCount": 6,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "47dc11ec-eaa9-4a33-96d9-df7a1a6c42df",
      "minLongitude": -2.1537,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.1436230291720926,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-22T03:10:00.000+0000",
      "estimatedRestoration": "2023-04-22T06:10:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KU7457'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KU7457",
      "maxLongitude": -2.1397,
      "minLatitude": 50.8264,
      "name": "DT11 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "DT11 9NX",
        "DT11 9PA"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.1537,
              50.8357
            ],
            [
              -2.1397,
              50.8357
            ],
            [
              -2.1397,
              50.8264
            ],
            [
              -2.1537,
              50.8264
            ],
            [
              -2.1537,
              50.8357
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.8357,
      "etrUpdate": true
    }
  ]
}
