{
  "Faults": [
    {
      "py/object": "Fault",
      "loggedAt": "2022-08-29T21:03:00.000+0000",
      "latitude": 51.07118472318643,
      "estimatedRestoration": "2022-08-30T00:30:00.000+0000",
      "message": "Weâ€™re sorry for the loss of supply. We currently have a fault affecting the areas listed. We are working hard to get the power back on as quickly as we can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JZ2566'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JZ2566",
      "reference": "JZ2566",
      "maxLongitude": -0.4032,
      "minLatitude": 51.0684,
      "name": "RH13 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "RH13 0RP",
        "RH13 0RR",
        "RH13 0SA"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.4111,
              51.0749
            ],
            [
              -0.4032,
              51.0749
            ],
            [
              -0.4032,
              51.0684
            ],
            [
              -0.4111,
              51.0684
            ],
            [
              -0.4111,
              51.0749
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-08-29T22:45:00.000+0000",
      "UUID": "b398a1ab-e15b-45af-84c0-62f347691d3b",
      "region": "com.opengrid.geo.world.europe.gb",
      "minLongitude": -0.4111,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "maxLatitude": 51.0749,
      "longitude": -0.4055406612327904,
      "resolved": false
    }
  ]
}
