{
  "Faults": [
    {
      "py/object": "Fault",
      "loggedAt": "2022-02-13T00:24:00.000+0000",
      "latitude": 51.367155958534674,
      "estimatedRestoration": "2022-02-13T12:00:00.000+0000",
      "message": "Weâ€™re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JM2704'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JM2704",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 51.36743,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -2.145
            },
            {
              "py/object": "Point",
              "latitude": 51.36776,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -2.14464
            },
            {
              "py/object": "Point",
              "latitude": 51.36701,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -2.14302
            },
            {
              "py/object": "Point",
              "latitude": 51.36667,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -2.14484
            },
            {
              "py/object": "Point",
              "latitude": 51.36743,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -2.145
            }
          ],
          "subCodes": [
            "SN12 6HT",
            "SN12 6HX",
            "SN12 6HY",
            "SN12 6JF",
            "SN12 6JG",
            "SN12 6JH"
          ],
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "JM2704",
      "engineerOnSiteTime": "2022-02-12T20:05:00.000+0000",
      "name": "SN12 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "SN12 6HT",
        "SN12 6HX",
        "SN12 6HY",
        "SN12 6JF",
        "SN12 6JG",
        "SN12 6JH"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          [
            [
              -2.145,
              51.36743
            ],
            [
              -2.14464,
              51.36776
            ],
            [
              -2.14302,
              51.36701
            ],
            [
              -2.14484,
              51.36667
            ],
            [
              -2.145,
              51.36743
            ]
          ]
        ],
        "type": "Polygon"
      },
      "UUID": "b08ba29d-4595-4706-b034-a13f02ae0fa7",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.1442993047456573,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-02-13T08:00:00.000+0000",
      "latitude": 56.34328063086501,
      "estimatedRestoration": "2022-02-13T09:00:00.000+0000",
      "message": "We're sorry for the loss of supply. The reason you're currently without power is a planned outage in the areas listed. We have turned off your electricity supply to allow us to safely carry out essential work to our electrical equipment. By doing this, it'll help us to improve the reliability of our service to you for the future. If you have any questions or require more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) with reference  '205292'. You will have received a letter from us confirming your power will be interrupted with specific information relating to your property. If you did not receive this letter, you can assume your power will not be interrupted.",
      "type": "PSI",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/205292",
      "reference": "205292",
      "name": "PH2 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "PH2 9LN"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -3.327097801716986,
          56.34328063086501
        ],
        "type": "Point"
      },
      "UUID": "cfb39849-ac81-4b2d-be7d-026f70bc4757",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -3.327097801716986,
      "resolved": false
    }
  ]
}
