{
  "Faults": [
    {
      "latitude": 51.787457470476504,
      "type": "LV",
      "reference": "KJ5072",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-01-02T11:50:00.000+0000",
      "affectedCustomerCount": 89,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "e638c5b1-e8f7-46f7-bdd9-a7cc2cf06e04",
      "minLongitude": -1.4971,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.494610700371554,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-01-02T10:23:00.000+0000",
      "estimatedRestoration": "2023-01-03T11:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KJ5072'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KJ5072",
      "maxLongitude": -1.4901,
      "minLatitude": 51.7857,
      "name": "OX28 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "OX28 6GZ",
        "OX28 6JL",
        "OX28 6LF",
        "OX28 6LG",
        "OX28 6LH",
        "OX28 6LN",
        "OX28 6LT",
        "OX28 6LY"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.4971,
              51.7892
            ],
            [
              -1.4901,
              51.7892
            ],
            [
              -1.4901,
              51.7857
            ],
            [
              -1.4971,
              51.7857
            ],
            [
              -1.4971,
              51.7892
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-01-02T12:00:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.7892,
      "etrUpdate": true
    },
    {
      "latitude": 51.71065349999771,
      "type": "LV",
      "reference": "KJ5274",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-01-02T21:00:00.000+0000",
      "affectedCustomerCount": 9,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "724e3d42-7c36-4944-80fe-97a97e7b60e5",
      "minLongitude": -1.0116,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.0055029836638438,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-01-02T18:48:00.000+0000",
      "estimatedRestoration": "2023-01-03T12:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KJ5274'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KJ5274",
      "maxLongitude": -0.9994,
      "minLatitude": 51.7096,
      "name": "OX9 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "OX9 7AB",
        "OX9 7BN",
        "OX9 7BW",
        "OX9 7DG"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.0116,
              51.7149
            ],
            [
              -0.9994,
              51.7149
            ],
            [
              -0.9994,
              51.7096
            ],
            [
              -1.0116,
              51.7096
            ],
            [
              -1.0116,
              51.7149
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-01-02T21:00:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.7149,
      "etrUpdate": true
    },
    {
      "latitude": 51.7873674391608,
      "type": "HV",
      "reference": "KJ5398",
      "etaUpdate": true,
      "affectedCustomerCount": 11,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "e5bc5459-6451-4671-a9d8-4ad0b2227502",
      "minLongitude": -1.4971,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.4945827106938403,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-01-03T05:46:00.000+0000",
      "estimatedRestoration": "2023-01-03T11:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KJ5398'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KJ5398",
      "maxLongitude": -1.4901,
      "minLatitude": 51.7857,
      "name": "OX28 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "OX28 6GZ",
        "OX28 6JL",
        "OX28 6LF",
        "OX28 6LG",
        "OX28 6LH",
        "OX28 6LN",
        "OX28 6LT",
        "OX28 6LY"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.4971,
              51.7892
            ],
            [
              -1.4901,
              51.7892
            ],
            [
              -1.4901,
              51.7857
            ],
            [
              -1.4971,
              51.7857
            ],
            [
              -1.4971,
              51.7892
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-01-03T07:20:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.7892,
      "etrUpdate": true
    },
    {
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-01-03T07:37:00.000+0000",
      "latitude": 51.8154430935619,
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. We are working hard to get the power back on as quickly as we can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KJ5413'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KJ5413",
      "reference": "KJ5413",
      "maxLongitude": -1.6271,
      "etaUpdate": true,
      "minLatitude": 51.806,
      "name": "OX18 Area",
      "otherUpdate": true,
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "OX18 4BE",
        "OX18 4BG",
        "OX18 4BH",
        "OX18 4BJ",
        "OX18 4BL",
        "OX18 4BQ",
        "OX18 4LU",
        "OX18 4LX",
        "OX18 4RG",
        "OX18 4TZ",
        "OX18 4UB",
        "OX18 4UH"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.6858,
              51.8298
            ],
            [
              -1.6271,
              51.8298
            ],
            [
              -1.6271,
              51.806
            ],
            [
              -1.6858,
              51.806
            ],
            [
              -1.6858,
              51.8298
            ]
          ]
        ],
        "type": "Polygon"
      },
      "UUID": "183e20eb-228b-4458-8de4-9d7c4428d2d4",
      "region": "com.opengrid.geo.world.europe.gb",
      "minLongitude": -1.6858,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "maxLatitude": 51.8298,
      "etrUpdate": true,
      "longitude": -1.6462691817660973,
      "resolved": false
    }
  ]
}
